import { FiAward, FiStar, FiZap } from 'react-icons/fi'

export const PLAN_OPTIONS = [
  {
    id: 'essential',
    name: 'Essencial',
    subtitle: 'Para começar a vender online',
    description: 'Para começar a vender online',
    priceMonthly: 59,
    priceAnnual: 590,
    equivalentMonthly: 49,
    commission: '+ 0% de comissão por venda',
    icon: FiZap,
    highlight: false,
    popular: false,
    cta: 'Começar agora',
    features: [
      '14 dias grátis inclusos',
      'Cardápio digital ilimitado',
      'Pedidos em tempo real',
      'Link próprio da loja',
      'Sem taxas por pedido',
      'Painel de controle',
      'Horários automáticos',
    ],
  },
  {
    id: 'professional',
    name: 'Profissional',
    subtitle: 'Mais escolhido pelos lojistas',
    description: 'Mais escolhido pelos lojistas',
    priceMonthly: 89,
    priceAnnual: 890,
    equivalentMonthly: 74,
    commission: '+ 0% de comissão por venda',
    icon: FiStar,
    highlight: true,
    popular: true,
    badge: 'Mais popular',
    cta: 'Começar agora',
    features: [
      '14 dias grátis inclusos',
      'Tudo do Essencial',
      'Cupons de desconto',
      'Taxa por bairro',
      'Campos personalizados',
      'Relatórios avançados',
      'WhatsApp integrado',
      'Suporte prioritário',
    ],
  },
  {
    id: 'premium',
    name: 'Premium',
    subtitle: 'Para quem quer vender mais',
    description: 'Para quem quer vender mais',
    priceMonthly: 159,
    priceAnnual: 1590,
    equivalentMonthly: 133,
    commission: '+ 0% de comissão por venda',
    icon: FiAward,
    highlight: false,
    popular: false,
    cta: 'Começar agora',
    features: [
      '14 dias grátis inclusos',
      'Tudo do Profissional',
      'Multi-loja até 3 unidades',
      'API de integração',
      'Domínio personalizado',
      'Marca branca',
      'Gerente de conta dedicado',
    ],
  },
]
